### ISSUE TITLE
Sapling texture

### ISSUE THREAD

**Issue by kingoscargames** [LordStephen77/Minetest2D#2]
I see that you used the sapling texture from minecraft, shouldnt that be changed?
Maybe to this: ![default_sapling](https://user-images.githubusercontent.com/29333817/27014260-6cf3e7f8-4ef5-11e7-8538-7f2136359457.png)
Maybe the mc texture is copyrighted or something

**Comment by LordStephen77** [comment]
The project will be modified in very short time. I've edited and rewritten almost everything. It will be completely renovated. The textures will be different and the game is very similar to Terraria. Thanks for your suggestions. I appreciate your interest in this project. I also changed the name of the game, I want to make it completely free.
