### ISSUE TITLE
player.png x3

### ISSUE THREAD

**Issue by kingoscargames** [LordStephen77/Minetest2D#4]
the same image but with a more detailed leg and arm animation:
<img width="60" alt="player" src="https://user-images.githubusercontent.com/29333817/27038175-78b8e120-4f8a-11e7-9ee5-d2dbdad75c9c.png">

**Comment by kingoscargames** [comment]
just posted this if anyone wants it

**Comment by kingoscargames** [comment]
why the +1?

**Comment by LordStephen77** [comment]
@kingoscargames Yes. As I said this project is deleted in a few hours, to be replaced with the new one. I redesigned the player by creating separate body parts to be managed in the code.

Now I sort things out and then update the repository.

**Comment by kingoscargames** [comment]
ok
